### ISSUE TITLE
Some helpful docs

### ISSUE THREAD

**Issue by extr3mal** [appium/appium-webdriveragent-driver#2]
Please include some docs of how to use this .

**Comment by Jonahss** [comment]
Docs will be coming. Still actively working on getting this project up and running.

If you install npm dependencies `npm install` and then run it with node `node .` it should start a server on port 4723 and then you can treat it like an appium server.

We will be including it as an optional backend in appium

**Comment by joshrlesch** [comment]
When trying to run `npm install` it is not completing and giving the following error
```
> appium-webdriveragent-driver@0.0.7 prepublish /Users/josh.lesch/Documents/github/appium-webdriveragent-driver
> gulp prepublish

module.js:339
    throw err;
    ^

Error: Cannot find module './build/lib/copySymlinks.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/josh.lesch/Documents/github/appium-webdriveragent-driver/gulpfile.js:3:20)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/4.2.1/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! appium-webdriveragent-driver@0.0.7 prepublish: `gulp prepublish`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-webdriveragent-driver@0.0.7 prepublish script 'gulp prepublish'.
npm ERR! This is most likely a problem with the appium-webdriveragent-driver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp prepublish
npm ERR! You can get their info via:
npm ERR!     npm owner ls appium-webdriveragent-driver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/josh.lesch/Documents/github/appium-webdriveragent-driver/npm-debug.log
```

**Comment by Jonahss** [comment]
@joshrlesch sorry about that. Just pushed a commit to fix that.

**Comment by Jonahss** [comment]
@extr3mal @joshrlesch Could I ask about your interest in this repository? I'll be looking for beta testers in a couple weeks when this gets into the main Appium server.

Plus, there will be a bunch more features we will have to build out over time. Are either of your able/interested in helping?

**Comment by joshrlesch** [comment]
Yes I would be interested. Currently we have a Appium/python framework for automated testing that runs in a selenium grid. We run tests on simulators and real devices. We need real device tests because the primary feature of our app in video recording.

Right now we down graded our node xcode version to 6.4 because of the xcode7 and instruments without delay issue.

Feel free to reach out and I can give you some more detail on our setup.

**Comment by extr3mal** [comment]
@Jonahss id be really happy to help at least for some period .

**Comment by Jonahss** [comment]
@extr3mal awesome. If you want you can send me an email: jonahss@gmail.com 

I will create some issues for this repository. Feel free to comment on any issue to say you would like to work on it ^.^

Or create issues with stuff you would like implemented.

Right now, we need to implement more methods, write more tests, add more desired capabilities, and have better error handling.

**Comment by Jonahss** [comment]
Real device support needs to be added too.
