### ISSUE TITLE
Can launch service but cant connect 

### ISSUE THREAD

**Issue by extr3mal** [appium/appium-webdriveragent-driver#3]
i was able to launch that but when i connect to server to test something server throws error
```
info iOSSim starting simulator with command: open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID 76FB941A-B0B4-40AF-B08D-0C7EF26421CC
info simctl Executing: xcrun with args: simctl list devices and timeout: 0
ERR! WebDriverAgent-driver TypeError: Cannot read property 'sdk' of undefined
ERR! WebDriverAgent-driver     at SimulatorXcode7.getPlatformVersion$ (lib/simulator-xcode-6.js:35:15)
ERR! WebDriverAgent-driver     at tryCatch (/Users/user/node_modules/appium-webdriveragent-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
ERR! WebDriverAgent-driver     at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/user/node_modules/appium-webdriveragent-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
ERR! WebDriverAgent-driver     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/user/node_modules/appium-webdriveragent-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
ERR! WebDriverAgent-driver     at GeneratorFunctionPrototype.invoke (/Users/user/node_modules/appium-webdriveragent-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
ERR! WebDriverAgent-driver     at run (/Users/user/node_modules/appium-webdriveragent-driver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
ERR! WebDriverAgent-driver     at /Users/user/node_modules/appium-webdriveragent-driver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
ERR! WebDriverAgent-driver     at flush (/Users/user/node_modules/appium-webdriveragent-driver/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
ERR! WebDriverAgent-driver     at process._tickCallback (node.js:355:11)
ERR! WebDriverAgent-driver  [TypeError: Cannot read property 'sdk' of undefined]
ERR! MJSONWP Encountered internal error running command: TypeError: Cannot read property 'quit' of null
ERR! MJSONWP     at WebDriverAgentDriver.deleteSession$ (lib/driver.js:81:19)
ERR! MJSONWP     at tryCatch (/Users/user/node_modules/appium-webdriveragent-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
ERR! MJSONWP     at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/user/node_modules/appium-webdriveragent-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
ERR! MJSONWP     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/user/node_modules/appium-webdriveragent-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
ERR! MJSONWP     at invoke (/Users/user/node_modules/appium-webdriveragent-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
ERR! MJSONWP     at enqueueResult (/Users/user/node_modules/appium-webdriveragent-driver/node_modules/babel-runtime/regenerator/runtime.js:185:17)
ERR! MJSONWP     at new Promise (/Users/user/node_modules/appium-webdriveragent-driver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:197:7)
ERR! MJSONWP     at AsyncIterator.enqueue (/Users/user/node_modules/appium-webdriveragent-driver/node_modules/babel-runtime/regenerator/runtime.js:184:16)
ERR! MJSONWP     at AsyncIterator.prototype.(anonymous function) [as next] (/Users/user/node_modules/appium-webdriveragent-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
ERR! MJSONWP     at Object.runtime.async (/Users/user/node_modules/appium-webdriveragent-driver/node_modules/babel-runtime/regenerator/runtime.js:209:12)
ERR! MJSONWP     at WebDriverAgentDriver.deleteSession (lib/driver.js:79:16)
ERR! MJSONWP     at WebDriverAgentDriver.createSession$ (lib/driver.js:70:18)
ERR! MJSONWP     at tryCatch (/Users/user/node_modules/appium-webdriveragent-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
ERR! MJSONWP     at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/user/node_modules/appium-webdriveragent-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
ERR! MJSONWP     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/user/node_modules/appium-webdriveragent-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
ERR! MJSONWP     at GeneratorFunctionPrototype.invoke (/Users/user/node_modules/appium-webdriveragent-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
```

**Comment by Jonahss** [comment]
Try using the XCUITest branch. things are more up to date there.

Unless you specifically want to run the webdriveragent version instead of the even newer XCUITest version?

Eventually I will split these two into separate repos.
